{% set name = "fockci" %}
{% set version = "0.1.0" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    git_url: git@github.com:shannonhouck/psi4fockci.git             # [linux]
    git_url: https://github.com/shannonhouck/psi4fockci.git         # [osx]
#    git_tag: v{{ version }}
    git_tag: master

build:
    noarch: python
    number: 2
#    number: 1                                               # [linux]
#    number: 0                                               # [osx]
#    skip: true                                              # [win]
    script: "{{ PYTHON }} -m pip install . --no-deps -vvv"

requirements:
    host:
#        - python {{ python }}
        - python >=3.6
        - setuptools
    run:
        - python >=3.6
#        - {{ pin_compatible('python', max_pin='x.x') }}

test:
    requires:
        - psi4 {{ psi4ver }}
        - pytest
    imports:
        - psi4fockci
        - psi4
    commands:
        # Verify module
        - test -f $SP_DIR/psi4fockci/__init__.py
        # Inspect linkage
        - conda inspect linkages --show-files --groupby=dependency fockci
        - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
        # Actually test
        - psi4 --test
        - pytest -rws --capture=sys $SP_DIR/psi4fockci -k "not 1x"
        - python -c "import psi4fockci as qc; import psi4; print('*** psi4fockci {} built successfully against Psi4 {}. Buy psinet a beer.'.format(qc.__version__, psi4.__version__))"

about:
    home: https://github.com/shannonhouck/psi4fockci
    dev_url: https://github.com/shannonhouck/psi4fockci
    doc_url: https://shannonhouck.github.io/psi4fockci/build/index.html
    doc_source_url: https://github.com/shannonhouck/psi4fockci/blob/master/docs/source/introduction.rst
    license: BSD-3-Clause
    license_url: https://opensource.org/licenses/BSD-3-Clause
    license_file: LICENSE
    license_family: BSD
    summary: "S. Houck's Fock-space CI (RAS-nSF-IP/EA) plugin to Psi4"
    # description: >

