{% set version = "0.3" %}

package:
    name: ambit
    version: {{ version }}

source:
    git_url: git@github.com:jturney/ambit.git            # [linux]
    git_url: https://github.com/jturney/ambit.git        # [osx]
    git_tag: v{{ version }}  # L0,1,M0: 0.3
    #git_tag: # 0.2: 9c7049a  # v0.2 + 37

build:
    number: 1                                            # [linux]
    number: 0                                            # [osx]
    binary_relocation: true
    skip: true                                           # [win]
    requires_features:
        blas: {{ blas_impl }}
    ignore_run_exports:
        # not using hdf5's fortran interface
        - libgfortran-ng
    run_exports:
        - {{ pin_subpackage('ambit', max_pin='x.x') }}

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake >=3.1
        - llvm-openmp                                   # [osx]
    host:
        - hdf5 {{ hdf5 }}
        - mkl-devel {{ mkl }}                           # [blas_impl == 'mkl']
        - openblas-devel {{ openblas }}                 # [blas_impl == 'openblas']
        - zlib {{ zlib }}
    run:
        - intel-openmp

test:
    commands:
        # Verify library and executable
        - test -f $PREFIX/lib/libambit$SHLIB_EXT
        # Inspect linkage
        - ldd -r -u $PREFIX/lib/libambit.so && return 0  # [linux]
        - ldd -v $PREFIX/lib/libambit.so                 # [linux]
        - otool -L $PREFIX/lib/libambit.dylib            # [osx]
        - conda inspect linkages --show-files --groupby=dependency ambit
        - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
    home: https://github.com/jturney/ambit
    dev_url: https://github.com/jturney/ambit
    # doc_url:
    # doc_source_url:
    license: LGPL-3.0
    license_url: https://opensource.org/licenses/LGPL-3.0
    license_file: COPYING.LESSER
    license_family: LGPL
    summary: "J. Turney's C++ library for the implementation of tensor product calculations"
    #description: >
