{% set version = "0.6" %}

package:
    name: ambit
    version: {{ version }}

source:
    git_url: git@github.com:jturney/ambit.git            # [linux]
    git_url: https://github.com/jturney/ambit.git        # [osx]
    #git_tag: v{{ version }}
    git_tag: 733c529                                     # L2M2: right zlib,  L1M1: right version

build:
    number: 2                                            # [linux]
    number: 2                                            # [osx]
    binary_relocation: true
    skip: true                                           # [win]
    requires_features:
        blas: {{ blas_impl }}
    ignore_run_exports:
        # not using hdf5's fortran interface
        - libgfortran-ng
    run_exports:
        - {{ pin_subpackage('ambit', max_pin='x.x') }}

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake >=3.16
        - ninja
        - llvm-openmp                                   # [osx]
        - pip                                           # [linux]
    host:
        - hdf5 {{ hdf5 }}
        - llvm-openmp 10.*                              # [osx]  # temp, I hope to avoid 10 and 12 dep
        - mkl-devel {{ mkl }}                           # [blas_impl == 'mkl']
        - openblas-devel {{ openblas }}                 # [blas_impl == 'openblas']
        - zlib {{ zlib }}
        - pybind11-headers {{ pybind11 }}
        - python {{ python }}
        - numpy >=1.12.0
    run:
        - intel-openmp                                  # [linux]
        - {{ pin_compatible('python', max_pin='x.x') }}
        - numpy

test:
    requires:
        - pytest
    imports:
        - ambit
    commands:
        # Verify library and module
        - test -f $PREFIX/lib/libambit$SHLIB_EXT                             # [unix]
        - if not exist %PREFIX%\\Library\\lib\\ambit.lib exit 1              # [win]
        - ls -l $SP_DIR/ambit                                                # [unix]
        - dir %SP_DIR%\ambit                                                 # [win]
        # Inspect linkage
        - ldd -r -u $PREFIX/lib/libambit$SHLIB_EXT && return 0               # [linux]
        - ldd -v $PREFIX/lib/libambit$SHLIB_EXT                              # [linux]
        - otool -L $PREFIX/lib/libambit$SHLIB_EXT                            # [osx]
        - conda inspect linkages --show-files --groupby=dependency ambit     # [unix]
        - conda inspect objects -p $PREFIX $PKG_NAME                         # [osx]
        # Test
        - pytest -rws --capture=sys $SP_DIR/ambit

about:
    home: https://github.com/jturney/ambit
    dev_url: https://github.com/jturney/ambit
    # doc_url:
    # doc_source_url:
    license: LGPL-3.0
    license_url: https://opensource.org/licenses/LGPL-3.0
    license_file: COPYING.LESSER
    license_family: LGPL
    summary: "J. Turney's C++ library for the implementation of tensor product calculations"
    #description: >


# History
    #git_tag: loriab-patch-1                                          # L1M3: mkl 2021 & pip        # v0.5.1
    #git_tag: v{{ version }}                                        # M1: hdf5 1.10.6 no intel-openmp
    #git_tag: v{{ version }}  # L0,1,M0: 0.3
    #git_tag: # 0.2: 9c7049a  # v0.2 + 37
