{% set version = "0.3" %}

package:
    name: gpu_dfcc
    version: {{ version }}

source:
    git_url: git@github.com:edeprince3/gpu_dfcc.git      # [linux]
    git_url: https://github.com/edeprince3/gpu_dfcc.git  # [osx]
    # git_tag: v{{ version }}
    git_tag: b98c6f1  # L2,3: 0.3 + 1 = b98c6f1
                      # L1: 0.3 = 16606bf

build:
    number: 3                                            # [linux]
    binary_relocation: true
    skip: true                                           # [win or osx]
    ignore_run_exports:
        - psi4

requirements:
    build:
        - cmake >=3.1
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    host:
        - cudatoolkit {{ cudatoolkit }}*                  # not used in build but pins the CUDA version for runtime
        - psi4                                            # initiate plugin and to link against
        - pybind11 {{ pybind11 }}
        - python {{ python }}
    run:
        - cudatoolkit {{ cudatoolkit }}*
        - {{ pin_compatible('python', max_pin='x.x') }}

test:
    requires:
        - psi4
    imports:
        - gpu_dfcc
        - psi4
    commands:
        # Verify module
        - test -f $SP_DIR/gpu_dfcc/gpu_dfcc.so
        - test -f $PREFIX/share/cmake/gpu_dfcc/gpu_dfccConfig.cmake
        # Inspect linkage
        - ldd -r -u $SP_DIR/gpu_dfcc/gpu_dfcc.so && return 0  # [linux]
        - ldd -v $SP_DIR/gpu_dfcc/gpu_dfcc.so                 # [linux]
        - otool -L $SP_DIR/gpu_dfcc/gpu_dfcc.so               # [osx]
        - conda inspect linkages --show-files --groupby=dependency gpu_dfcc
        - conda inspect objects -p $PREFIX $PKG_NAME                  # [osx]
        - grep -r theoryfs2 $PREFIX/share/cmake/ || true      # [linux]
        # Actually test
        - psi4 --test
        - python -c "import gpu_dfcc, sys; sys.exit(gpu_dfcc.test('long', extras=['-k', 'psiapi']))"
        - python -c "import gpu_dfcc, psi4; print('*** gpu_dfcc {} built successfully against Psi4 {}. Buy psinet a beer.'.format(gpu_dfcc.__version__, psi4.__version__))"

about:
    home: https://github.com/edeprince3/gpu_dfcc
    dev_url: https://github.com/edeprince3/gpu_dfcc
    doc_url: https://github.com/edeprince3/gpu_dfcc/blob/master/README.md
    # doc_source_url:
    license: GPL-2.0+
    license_url: https://opensource.org/licenses/GPL-2.0+
    license_file: LICENSE
    license_family: GPL
    summary: "E. DePrince's GPU-accelerated coupled-cluster with density fitting plugin to Psi4"
    # description: >

# NOTES
# -----

# * To build against a certain, non-latest psi4, `req/host` will be e.g., `psi4 1.1+add49b9`
