{% set name = "openfermion" %}
{% set version = "0.9" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    git_url: git@github.com:quantumlib/OpenFermion.git              # [linux]
    git_url: https://github.com/quantumlib/OpenFermion.git          # [osx]
    # git_tag: v{{ version }}
    git_tag: 0.9.0  # L0/M0: 0.9 = 9c2e029  # L1/M1: defaults cvxopt  # L2: scipy v1 constriant, drop cvxopt

build:
    number: 2                                               # [linux]
    number: 1                                               # [osx]
    skip: true                                              # [win]

requirements:
    host:
        - python {{ python }}
        - setuptools
    run:
        - future
        - h5py >=2.8
        - hdf5 {{ hdf5 }}*                                  # explicit (from hdf5) for pinning
        - networkx
        - numpy >=1.11.0
        - {{ pin_compatible('python', max_pin='x.x') }}
        - scipy >=1.1.0,<1.3                                # max only until new release when special.comb, not misc.comb, see also temp line in psi4-rt

test:
    requires:
        - ipykernel
        - matplotlib
        - nbconvert
        - pubchempy
        - pytest
    imports:
        - openfermion
    commands:
        # Verify module
        - test -f $SP_DIR/openfermion/__init__.py
        # Inspect linkage
        - conda inspect linkages --show-files --groupby=dependency openfermion
        - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
        # Actually test
        - pytest -rws --capture=sys $SP_DIR/openfermion

about:
    home: https://www.openfermion.org
    dev_url: https://github.com/quantumlib/OpenFermion
    doc_url: http://openfermion.readthedocs.io/en/latest/openfermion.html
    doc_source_url: https://github.com/quantumlib/OpenFermion/tree/master/docs
    license: Apache-2.0
    license_url: https://opensource.org/licenses/Apache-2.0
    license_file: LICENSE
    license_family: APACHE
    summary: "Google's electronic structure package for quantum computers"
    # description: >

# History
#
# * {% set version = "0.7" %}
#    git_tag: 7734093  # v0.7 + 1 (installed testing)
