{% set name = "openfermionpsi4" %}
{% set version = "0.4" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    git_url: git@github.com:quantumlib/OpenFermion-Psi4.git              # [linux]
    git_url: https://github.com/quantumlib/OpenFermion-Psi4.git          # [osx]
    # git_tag: v{{ version }}
    git_tag: c6b0a37  # L1: of 0.10, L0: 0.4 = c6b0a37

build:
    number: 1                                               # [linux]
    number: 0                                               # [osx]
    skip: true                                              # [win]
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python {{ python }}
        - setuptools
    run:
        - openfermion >={{ openfermion }}
        - {{ pin_compatible('python', max_pin='x.x') }}

test:
    requires:
        - psi4
    imports:
        - openfermionpsi4
        - psi4
    files:
        - tests/demo.py
    commands:
        # Verify module
        - test -f $SP_DIR/openfermionpsi4/__init__.py
        # Inspect linkage
        - conda inspect linkages --show-files --groupby=dependency openfermionpsi4 openfermion
        - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
        # Actually test
        - ${PYTHON} tests/demo.py

about:
    home: https://www.openfermion.org
    dev_url: https://github.com/quantumlib/OpenFermion-Psi4
    # doc_url:
    # doc_source_url:
    license: LGPL-3.0
    license_url: https://opensource.org/licenses/LGPL-3.0
    license_file: LICENSE
    license_family: LGPL
    summary: "Google's plugin allowing OpenFermion to interface with Psi4"
    # description: >

# History
#
# * {% set version = "0.3" %}
#    git_tag: 98d94cf  # v0.3 + 2 (fix encoding)
