{% set version = "1.2" %}

package:
    name: dkh
    version: {{ version }}

source:
    git_url: git@github.com:psi4/dkh.git                 # [linux]
    git_url: https://github.com/psi4/dkh.git             # [osx]
    git_tag: 6f02ca0  # v1.2 + 2

build:
    number: 2                                            # [linux]
    number: 3                                            # [osx]
    binary_relocation: true
    skip: true                                           # [win]
    run_exports:
        - {{ pin_subpackage('dkh', max_pin='x.x') }}
    ignore_run_exports:
        # unused libraries
        - libgcc-ng
        - libgfortran-ng

requirements:
    build:
        - cmake >=3.0
        - {{ compiler('c') }}                            # [osx]
        - {{ compiler('fortran') }}
        - llvm-openmp                                    # [osx]
        - intel-openmp                                   # [osx]

test:
    commands:
        # Verify library
        - test -f $PREFIX/lib/libdkh$SHLIB_EXT
        # Inspect linkage
        - ldd -r -u $PREFIX/lib/libdkh.so              # [linux]
        - ldd -v $PREFIX/lib/libdkh.so                 # [linux]
        - otool -L $PREFIX/lib/libdkh.dylib            # [osx]
        - conda inspect linkages --show-files --groupby=dependency dkh
        - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]

about:
    home: http://www.reiher.ethz.ch/software/dkh-x2c.html
    dev_url: https://github.com/psi4/dkh
    # doc_url:
    # doc_source_url:
    license: LGPL-3.0
    license_url: https://opensource.org/licenses/LGPL-3.0
    license_file: COPYING.LESSER
    license_family: LGPL
    summary: "Wolf, Reiher, and Hess's Douglas-Kroll-Hess (DKH) relativistic correction"
    # description: >
