package:
  name: mdsapt
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  git_url: https://github.com/ALescoulie/MDSAPT.git
  git_tag: 1.0.0

about:
  home: https://github.com/ALescoulie/MDSAPT
  license: GPL-3.0
  license_file: LICENSE
  license_family: GPL3
  summary: SAPT Calculations for MDAnalysis
  doc_url: https://mdsapt.readthedocs.io/
  dev_url: https://github.com/ALescoulie/MDSAPT

build:
  # MDSAPT does not support windows.
  skip: True # [win]

requirements:
  host:
    - python
    - pip
  run:
    - psi4
    - mdanalysis
    - nglview
    - numpy
    - openmm
    - pandas
    - pdbfixer
    - python
    - pyyaml
    - rdkit

test:
  imports:
    - mdsapt
    - mdsapt.tests
  source_files:
    - mdsapt/**/*
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v mdsapt

extra:
  maintainers:
   - ALescoulie
   - astralbijection
  recipe-maintainers:
   - ALescoulie
   - astralbijection
