{% set version = "2.7.1" %}

package:
    name: libint2
    version: {{ version }}

source:
    #url: https://github.com/loriab/libint/releases/download/v0.1/Libint2-export-7-7-0-10-7-0_0.tgz  # [linux] Susi
    #url: https://github.com/loriab/libint/releases/download/v0.1/Libint2-export-7-7-4-7-7-5_1.tgz  # [linux]  # longstanding v1.4, v1.5
    #url: https://github.com/loriab/libint/releases/download/v0.1/Libint2-export-5-4-3-6-5-4_1.tgz  # [osx or win]  # longstanding v1.4, v1.5
    #url: https://github.com/loriab/libint/releases/download/v0.1/Libint2-export-5-4-3-6-5-4_mm25.tgz  # [linux] mm25sss
    #url: https://github.com/loriab/libint/releases/download/v0.1/Libint2-export-5-4-3-6-5-4_mm25f12.tgz  # [linux] mm25sssf12
    #url: https://github.com/loriab/libint/releases/download/v0.1/Libint2-export-5-4-3-6-5-4_mm25f12ob2.tgz  # mm25sssf12ob2
    #url: https://github.com/loriab/libint/releases/download/v0.1/Libint2-export-5-4-3-6-5-4_mm0f12ob2pd.tgz  # [linux] mm0sssf12ob2pd
    ##url: https://github.com/loriab/libint/releases/download/v0.1/Libint2-export-4-3---5-4--_mm4ob2.tgz  # 4354_mm4ob2
    #url: https://github.com/loriab/libint/releases/download/v0.1/Libint2-export-5-4-3-6-5-4_mm4ob2.tgz  # 543654_mm4ob2
    url: https://github.com/loriab/libint/releases/download/v0.1/Libint2-export-5-4-3-6-5-4_mm4f12ob2.tgz  # [osx] mm4f12ob2 2.7.1


build:
    #number: 9                                            # [linux]  # 9 is am7_1 w/boost
    #number: 14                                           # [linux]  # 14 is mm0sssf12ob2pd but gss and constexpr=0. 13 is same src as 12 but gss. 12 is mm25sssf12ob2. 11 is mm25sssf12. 10 is mm25sss.
    #number: 3                                            # [osx]    # 3 is am5_1 w/boost
    number: 8                                            # [osx]     # 8 is mm4f12ob2 as sss (bumped v to 2.7.1). 7 is mm4f12ob2 as gss (v still 2.6.0). 6 is 543654_mm4ob2. 5 is trial 4354_mm4ob2.tgz. 4 is mm25sssf12ob2 but gss.
    #number: 0                                            # [win]
    #number: 3                                            # [win]    # 3 (JMT) is same src as 2 but gss. 2 (JMT) is mm25sssf12ob2.
    binary_relocation: true
    run_exports:
        - {{ pin_subpackage('libint2', max_pin='x') }}

requirements:
    build:
        - cmake >=3.8
        - {{ compiler('cxx') }}
        - ninja
    host:
        # want NO boost so that include/libint2/boost/ installs
        - eigen

test:
    commands:
        # Verify library
        - test -f $PREFIX/lib/libint2$SHLIB_EXT
        # Inspect linkage
        - ldd -r -u $PREFIX/lib/libint2.so && return 0 # [linux]
        - ldd -v $PREFIX/lib/libint2.so                # [linux]
        - otool -L $PREFIX/lib/libint2.dylib           # [osx]
        - conda-inspect linkages libint2 --show-files

about:
    home: https://github.com/evaleev/libint
    dev_url: https://github.com/evaleev/libint
    doc_url: http://evaleev.github.io/libint/
    doc_source_url: https://github.com/evaleev/libint/blob/master/doc/progman/progman.tex
    license: LGPL-3.0+
    license_url: https://opensource.org/licenses/LGPL-3.0+
    license_file: LICENSE
    license_family: LGPL
    summary: "E. Valeev and J. Fermann's two-body Gaussian molecular integrals"
    # description: >


# NOTES
# -----

# * history toward production build
     #url: https://github.com/loriab/libint/releases/download/v0.1/Libint2-export-7-7-4-7-7-5_0.tgz  # L8
     #url: https://github.com/loriab/libint/releases/download/v0.1/Libint2-export-5-4-3-6-5-4_0.tgz  # L7
     #url: https://github.com/loriab/libint/releases/download/v0.1/Libint2-export31-7-7-4.tgz
     #url: https://github.com/loriab/libint/releases/download/v0.1/Libint2-export29-7-7-5.tgz
     #url: https://github.com/loriab/libint/releases/download/v0.1/Libint2-export-7-7-5.tgz
     #url: https://github.com/loriab/libint/archive/ebe3fad10e7b44ea69dd07709e42293f6286279f.zip  # Sept loriab repo
     #url: https://github.com/loriab/libint/archive/8f26ac59822b093e35cd528119d9efc8c1d31b8e.zip

     #build/number: 8  # [linux]  # 9 is am7_1 w/boost, # 8 is am7 # 7 is for med 543z w/o center_dep w/eri3_e4 # 6 is for am7;7;5 # 5 is for am6;6;5 # 4 is to have components and fma # 3 is to get tarball # 2 turns off sph eri3
     #build/number: 3  # [osx]    # 3 is am5_1 w/boost, 2 is build36 to have clang 10,  1 is build30

# * tried to build an AM6 for linux build/number: 2 at libint2_1574565922374 but it stopped compiling. could be fixable

# * history toward production build
    #url: https://github.com/loriab/libint/releases/download/v0.1/Libint2-export-7-7-4-7-7-5_0.tgz  # L8
    #url: https://github.com/loriab/libint/releases/download/v0.1/Libint2-export-5-4-3-6-5-4_0.tgz  # L7
    #url: https://github.com/loriab/libint/releases/download/v0.1/Libint2-export31-7-7-4.tgz
    #url: https://github.com/loriab/libint/releases/download/v0.1/Libint2-export29-7-7-5.tgz
    #url: https://github.com/loriab/libint/releases/download/v0.1/Libint2-export-7-7-5.tgz
    #url: https://github.com/loriab/libint/archive/ebe3fad10e7b44ea69dd07709e42293f6286279f.zip  # Sept loriab repo
    #url: https://github.com/loriab/libint/archive/8f26ac59822b093e35cd528119d9efc8c1d31b8e.zip

    #build/number: 8  # [linux]  # 8 is copy-in # 7 is for med 543z w/o center_dep w/eri3_e4 # 6 is for am7;7;5 # 5 is for am6;6;5 # 4 is to have components and fma # 3 is to get tarball # 2 turns off sph eri3
