
{% set data = load_setup_py_data(setup_file='conda/_conda_vers.py') %}
{% set libefp_version = "1.5.0" %}

package:
    name: libefp-multiout
    version: {{ data.get('version') }}

source:
    git_url: git@github.com:loriab/pylibefp.git         # [linux]
    git_url: https://github.com/loriab/pylibefp.git     # [osx]
    # git_tag: v{{ version }}
    git_tag: v0.5

build:
    number: 3                                            # [linux]
    number: 2                                            # [osx]
    binary_relocation: true
    skip: true                                           # [win]

requirements:
    build:
        - cmake >=3.8
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    host:
        - mkl-devel {{ mkl }}                           # [blas_impl == 'mkl']
        - openblas-devel {{ openblas }}                 # [blas_impl == 'openblas']
        - pybind11 {{ pybind11 }}  # trouble at dep metadata time
        - python {{ python }}
        - qcelemental {{ qcelemental }}
        # docs
        - python-graphviz                               # [linux and py==37]
        - sphinx >=1.5,<2                               # [linux and py==37]
        - sphinx-automodapi                             # [linux and py==37]
        - sphinx-psi-theme                              # [linux and py==37]

outputs:
    - name: libefp
      version: {{ libefp_version }}
      build:
          run_exports:
              - {{ pin_subpackage('libefp', max_pin='x.x.x') }}
          ignore_run_exports:
              # gcc symbols linked statically
              - libgcc-ng                               # [linux]
      requirements:
          build:
              - {{ compiler('c') }}
          host:
              - mkl-devel {{ mkl }}                           # [blas_impl == 'mkl']
              - openblas-devel {{ openblas }}                 # [blas_impl == 'openblas']
      files:
          - include/efp.h
          - include/libefp/*
          - lib/libefp.so*                                    # [linux]
          - lib/libefp.*dylib                                 # [osx]
          - share/cmake/libefp/*
          - share/libefp/*
          - share/libefp/fraglib/*
      test:
          commands:
              # Verify library
              - test -f $PREFIX/lib/libefp$SHLIB_EXT
              - test -f $PREFIX/include/libefp/efp.h
              - test -f $PREFIX/share/libefp/fraglib/h2.efp
              - test -f $PREFIX/share/cmake/libefp/libefpConfig.cmake
              # Inspect linkage
              - ldd -r -u $PREFIX/lib/libefp.so && return 0  # [linux]
              - ldd -v $PREFIX/lib/libefp.so                 # [linux]
              - otool -L $PREFIX/lib/libefp.dylib            # [osx]
              - conda inspect linkages --show-files --groupby=dependency libefp
              - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]
      about:
          home: https://github.com/ilyak/libefp
          dev_url: https://github.com/ilyak/libefp/blob/master/README.md
          doc_url: https://libefp.github.io/
          # doc_source_url:
          license: BSD-2-Clause
          license_url: https://opensource.org/licenses/BSD-2-Clause
          license_file: LICENSE
          license_family: BSD
          summary: "I. Kaliman's parallel implementation of the Effective Fragment Potential (EFP) method"
          # description: >

    - name: pylibefp
      build:
          ignore_run_exports:
              # # gcc symbols linked statically
              # - libgcc-ng
              - libstdcxx-ng                                 # [linux]
      requirements:
          build:
              - {{ compiler('cxx') }}
          host:
              - {{ pin_subpackage('libefp', exact=True) }}
              - pybind11 {{ pybind11 }}
              - python {{ python }}
              - qcelemental {{ qcelemental }}
          run:
              - {{ pin_subpackage('libefp', exact=True) }}
              - {{ pin_compatible('python', max_pin='x.x') }}
              - {{ pin_compatible('qcelemental', max_pin='x') }}
      files:
          - lib/python*/site-packages/pylibefp/*
          - lib/python*/site-packages/pylibefp/tests/*
          - share/cmake/pylibefp/*
      test:
          requires:
              - numpy
              # - psi4 >= 1.2a1.dev507
              - pytest
          commands:
              - export PYLIB_EXT=`$PYTHON -c 'import sysconfig as s; print(s.get_config_var("EXT_SUFFIX"))'`
              # Verify existence and execution
              - test -f $SP_DIR/pylibefp/core$PYLIB_EXT
              # Inspect linkage
              - ldd -r -u $SP_DIR/pylibefp/core$PYLIB_EXT && return 0  # [linux]
              - ldd -v $SP_DIR/pylibefp/core$PYLIB_EXT                 # [linux]
              - otool -L $SP_DIR/pylibefp/core$PYLIB_EXT               # [osx]
              - conda inspect linkages --show-files --groupby=dependency pylibefp libefp
              - conda inspect objects -p $PREFIX $PKG_NAME     # [osx]
              # Actually test
              - conda list
              - python -c "import pylibefp; pylibefp.test(); print('*** PylibEFP {} built successfully. Buy psinet a beer.'.format(pylibefp.__version__))"
      about:
          home: https://github.com/loriab/pylibefp
          dev_url: https://github.com/loriab/pylibefp/blob/master/README.md
          doc_url: http://psicode.org/pylibefpmanual/master/index.html
          doc_source_url: https://github.com/loriab/pylibefp/blob/master/doc/source/introduction.rst
          license: BSD-3-Clause
          license_url: https://opensource.org/licenses/BSD-3-Clause
          license_file: LICENSE
          license_family: BSD
          summary: "L. A. Burns's python bindings to libefp"
          # description: >

    - name: pylibefp-docs
      build:
           number: 0
           skip: true  # [win or osx or not py==37]
      requirements:
          host:
              - python {{ python }}
              - python-graphviz
              - sphinx >=1.5
              - sphinx-automodapi
              - sphinx-psi-theme
      files:
          - share/doc/pylibefp
      test:
          commands:
              - test -f $PREFIX/share/doc/pylibefp/html/index.html

# NOTES
# -----

# source/path: ../../../pylibefp

# HISTORY
#   source/git_tag: 07ec7e9  # 1: 0.4.dev6 = v0.3-7-g07ec7e9  0: e84aa39 = 0.3.dev2
#   source/git_tag: v0.4   build/number L1M1
