{% set version = "2.0.2" %}

package:
    name: gcp
    version: {{ version }}

source:
    fn: gcp_v202.tar.gz
    url: https://www.chemie.uni-bonn.de/pctc/mulliken-center/software/gcp/gcp_v202.tar.gz

build:
    number: 1                                            # [linux]
    number: 0                                            # [osx]
    binary_relocation: true
    skip: true                                           # [win]
    ignore_run_exports:
        # unused libraries
        - libgcc-ng
        - libgfortran-ng

requirements:
    build:
        - {{ compiler('fortran') }}

test:
    commands:
        # Verify executable
        - test -f $PREFIX/bin/gcp
        - $PREFIX/bin/gcp -h
        # Inspect linkage
        - otool -L $PREFIX/bin/gcp                       # [osx]
        - conda inspect linkages --show-files --groupby=dependency gcp
        - conda inspect objects -p $PREFIX $PKG_NAME     # [osx]

about:
    home: https://www.chemie.uni-bonn.de/pctc/mulliken-center/software/gcp/gcp
    # dev_url:
    doc_url: https://www.chemie.uni-bonn.de/pctc/mulliken-center/software/gcp/manGCP.pdf
    # doc_source_url:
    license: GPL-1.0+
    # license_url:
    # license_file:
    license_family: GPL
    summary: "S. Grimme's geometrical counterpoise correction for DFT and Hartree--Fock quantum chemical methods"
    # description: >
