{% set version = "1.1.0" %}

package:
    name: mp2d
    version: {{ version }}

source:
    git_url: git@github.com:Chandemonium/MP2D.git        # [linux]
    git_url: https://github.com/Chandemonium/MP2D.git    # [osx]
    # git_tag: v{{ version }}
    git_tag: c6c7f86

build:
    number: 0                                            # [linux]
    number: 0                                            # [osx]
    binary_relocation: true
    skip: true                                           # [win]

requirements:
    build:
        - cmake >=3.5
        - {{ compiler('cxx') }}

test:
    commands:
        # Verify executable
        - test -f $PREFIX/bin/mp2d
        - test -f $PREFIX/share/mp2d/mp2d_parameters.dat
        - $PREFIX/bin/mp2d --version
        # Inspect linkage
        - otool -L $PREFIX/bin/mp2d           # [osx]
        - conda inspect linkages --show-files --groupby=dependency mp2d
        - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]

about:
    # home:
    dev_url: https://github.com/Chandemonium/MP2D.git
    # doc_url:
    # doc_source_url:
    license: MIT
    license_url: https://opensource.org/licenses/MIT
    # license_file:
    license_family: MIT
    summary: "C. Greenwell's dispersion correction for MP2 quantum chemical method"
    # description: >


# History
# -------

# orig repo
#   {% set version = "0.1.0" %}
#       git_url: git@github.com:loriab/mp2d_cpp.git          # [linux]
#       git_url: https://github.com/loriab/mp2d_cpp.git      # [osx]
#        - test -f $PREFIX/share/mp2d/Params.txt
#    ignore_run_exports:
#        # unused libraries
#        - libgcc-ng                                      # [linux]
#        - libstdcxx-ng                                   # [linux]
