{% set data = load_setup_py_data(setup_file='conda/_conda_vers.py') %}

package:
    name: helpme
    version: {{ data.get('version') }}

source:
    git_url: git@github.com:loriab/helpme.git           # [linux]
    #git_url: git@github.com:andysim/helpme.git           # [linux]
    #git_url: https://github.com/andysim/helpme.git       # [osx]
    #git_tag: 3f14ff0  # v1, ~1.2.1
    git_tag: cmakelab

build:
    number: 0                                            ## [linux]  # 4: AVX-512
    number: 0                                            ## [osx]
    binary_relocation: true
    skip: true                                           ## [win]
    run_exports:
        - {{ pin_subpackage('helpme', max_pin='x.x') }}

requirements:
    build:
        - cmake >=3.10
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
    host:
        - mkl-devel {{ mkl }}                           # [blas_impl == 'mkl']
        - pybind11 {{ pybind11 }}
        - python {{ python }}
        - numpy
        - pytest  # b/c internal testing
    run:
        - intel-openmp
        - {{ pin_compatible('python', max_pin='x.x') }}
        - numpy

test:
    requires:
        - pytest
    imports:
        - helpme
    commands:
        # Verify library
        - test -f $PREFIX/lib/libhelpme$SHLIB_EXT
        # Inspect linkage
        - ldd -r -u $PREFIX/lib/libhelpme.so && return 0  # [linux]
        - ldd -v $PREFIX/lib/libhelpme.so                 # [linux]
        - otool -L $PREFIX/lib/libhelpme.dylib            # [osx]
        - conda-inspect linkages helpme --show-files
        # Actually test
        - $PYTHON -m pytest --pyargs helpme

about:
    home: https://github.com/andysim/helpme
    dev_url: https://github.com/andysim/helpme
    # doc_url:
    doc_source_url: https://github.com/andysim/helpme/tree/master/docs/sphinx/index.rst
    license: BSD-3-Clause
    license_url: https://opensource.org/licenses/BSD-3-Clause
    license_file: LICENSE
    license_family: BSD
    summary: "A. Simmonett's efficient library for particle mesh Ewald"
    # description: >
